# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'P-Alarm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for P-Alarm
  # Rx
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'

  # Others
    pod 'SnapKit'
    pod 'Then'

end
